{"content":"\r\n<div style=\"display:none\">\r\n\t\r\n</div>\r\n\r\n  \r\n  <h1>\r\n    <span class=\"lang-csharp\">Exception</span>\r\n    \t\t\t\tClass\r\n  </h1>\r\n  \r\n  <h2 class=\"hiddenAnchor\">Definition</h2>\r\n  \r\n  <div class=\"metadata\">\r\n  \r\n  \r\n  </div>\r\n  \r\n  <div class=\"summaryHolder\">\r\n  \t<div class=\"summary\">\r\n  \t\t<p>Represents errors that occur during application execution.  </p>\n<p> To browse the .NET Framework source code for this type, see the <a href=\"http://referencesource.microsoft.com/#mscorlib/system/exception.cs#f092fb2b893a0162\" data-linktype=\"external\">Reference Source</a>.</p>\n\r\n  \t</div>\r\n  </div><nav id=\"center-doc-outline\" class=\"doc-outline\" ms.cmpgrp=\"intopic toc\" role=\"navigation\" aria-label=\"On page navigation\">\r\n    <h3>In this Article</h3>\r\n  </nav>\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\">[System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.None)]\n[System.Runtime.InteropServices.ComDefaultInterface(typeof(System.Runtime.InteropServices._Exception))]\n[System.Runtime.InteropServices.ComVisible(true)]\npublic class Exception : System.Runtime.InteropServices._Exception, System.Runtime.Serialization.ISerializable</code></pre>\r\n  \r\n  \r\n  \r\n  \r\n  \t<dl class=\"attributeList stack\">\r\n  \t\t<dt>Inheritance</dt><dd>\r\n  \t\t<div class=\"pdlHolder\">\r\n  \t\t\t<div class=\"pdl\"><span class=\"lang-csharp\"><a class=\"xref\" href=\"system.object\" data-linktype=\"relative-path\">System.Object</a></span></div>\r\n  \t\t\t<span class=\"lang-csharp\">Exception</span>\r\n  \t\t</div>\r\n  \t\t</dd>\r\n  \t</dl>\r\n  \r\n  \r\n  \r\n  \r\n  \t<h3 class=\"accented\">Inherited Members</h3>\r\n  \t<h4 class=\"accented\"></h4>\r\n  \t<div class=\"cdlHolder\">\r\n  \t\t\t<div class=\"cdl\"><span class=\"lang-csharp\"><a class=\"xref\" href=\"system.object#System_Object_Equals_System_Object_\" data-linktype=\"relative-path\">Equals(Object)</a></span></div>\r\n  \t\t\t<div class=\"cdl\"><span class=\"lang-csharp\"><a class=\"xref\" href=\"system.object#System_Object_Equals_System_Object_System_Object_\" data-linktype=\"relative-path\">Equals(Object,Object)</a></span></div>\r\n  \t\t\t<div class=\"cdl\"><span class=\"lang-csharp\"><a class=\"xref\" href=\"system.object#System_Object_GetHashCode\" data-linktype=\"relative-path\">GetHashCode()</a></span></div>\r\n  \t\t\t<div class=\"cdl\"><span class=\"lang-csharp\"><a class=\"xref\" href=\"system.object#System_Object_MemberwiseClone\" data-linktype=\"relative-path\">MemberwiseClone()</a></span></div>\r\n  \t\t\t<div class=\"cdl\"><span class=\"lang-csharp\"><a class=\"xref\" href=\"system.object#System_Object_ReferenceEquals_System_Object_System_Object_\" data-linktype=\"relative-path\">ReferenceEquals(Object,Object)</a></span></div>\r\n  \t</div>\r\n  \r\n  \t<h2 class=\"accented\">Remarks</h2>\r\n  \t<div class=\"NOTE\"><h5>Note</h5><p> To view the .NET Framework source code for this type, see the <a href=\"http://referencesource.microsoft.com/#mscorlib/system/exception.cs#f092fb2b893a0162\" data-linktype=\"external\">Reference Source</a>. You can browse through the source code online, download the reference for offline viewing, and step through the sources (including patches and updates) during debugging; see <a href=\"http://referencesource.microsoft.com/\" data-linktype=\"external\">instructions</a>.  </p>\n</div>\n<p> This class is the base class for all exceptions. When an error occurs, either the system or the currently executing application reports it by throwing an exception that contains information about the error. After an exception is thrown, it is handled by the application or by the default exception handler.  </p>\n<p> In this section:  </p>\n<p> <a href=\"#Errors\" data-linktype=\"self-bookmark\">Errors and exceptions</a><br> <a href=\"#TryCatch\" data-linktype=\"self-bookmark\">Try/catch blocks</a><br> <a href=\"#Features\" data-linktype=\"self-bookmark\">Exception type features</a><br> <a href=\"#Properties\" data-linktype=\"self-bookmark\">Exception class properties</a><br> <a href=\"#Performance\" data-linktype=\"self-bookmark\">Performance considerations</a><br> <a href=\"#Rethrow\" data-linktype=\"self-bookmark\">Re-throwing an exception</a><br> <a href=\"#Standard\" data-linktype=\"self-bookmark\">Choosing standard exceptions</a><br> <a href=\"#Custom\" data-linktype=\"self-bookmark\">Implementing custom exceptions</a>  </p>\n<p><a name=\"Errors\"></a>   </p>\n<h2 id=\"errors-and-exceptions\">Errors and exceptions</h2>\n<p> Run-time errors can occur for a variety of reasons. However, not all errors should be handled as exceptions in your code. Here are some categories of errors that can occur at run time and the appropriate ways to respond to them.  </p>\n<ul>\n<li><p><strong>Usage errors.</strong> A usage error represents an error in program logic that can result in an exception. However, the error should be addressed not through exception handling but by modifying the faulty code. For example, the override of the <a class=\"xref\" href=\"system.object#System_Object_Equals_System_Object_\" data-linktype=\"relative-path\">System.Object.Equals(Object)</a> method in the following example assumes that the <code>obj</code> argument must always be non-null.  </p>\n<pre><code class=\"lang-vb\" name=\"System.Exception.Class#4\">Public Class Person\n   Private _name As String\n   \n   Public Property Name As String\n      Get\n         Return _name\n      End Get\n      Set\n         _name = value\n      End Set\n   End Property\n   \n   Public Overrides Function Equals(obj As Object) As Boolean\n      &#39; This implementation contains an error in program logic:\n      &#39; It assumes that the obj argument is not null.\n      Dim p As Person = CType(obj, Person)\n      Return Me.Name.Equals(p.Name)\n   End Function\nEnd Class\n\nModule Example\n   Public Sub Main()\n      Dim p1 As New Person()\n      p1.Name = &quot;John&quot;\n      Dim p2 As Person = Nothing\n      \n      &#39; The following throws a NullReferenceException.\n      Console.WriteLine(&quot;p1 = p2: {0}&quot;, p1.Equals(p2))   \n   End Sub\nEnd Module\n</code></pre><pre><code class=\"lang-cs\" name=\"System.Exception.Class#4\">using System;\n\npublic class Person\n{\n   private string _name;\n   \n   public string Name \n   {\n      get { return _name; } \n      set { _name = value; }\n   }\n   \n   public override int GetHashCode()\n   {\n      return this.Name.GetHashCode();  \n   }  \n                        \n   public override bool Equals(object obj)\n   {\n      // This implementation contains an error in program logic:\n      // It assumes that the obj argument is not null.\n      Person p = (Person) obj;\n      return this.Name.Equals(p.Name);\n   }\n}\n\npublic class Example\n{\n   public static void Main()\n   {\n      Person p1 = new Person();\n      p1.Name = &quot;John&quot;;\n      Person p2 = null; \n      \n      // The following throws a NullReferenceException.\n      Console.WriteLine(&quot;p1 = p2: {0}&quot;, p1.Equals(p2));   \n   }\n}\n</code></pre><p> The <a class=\"xref\" href=\"system.nullreferenceexception\" data-linktype=\"relative-path\">NullReferenceException</a> exception that results when <code>obj</code> is <code>null</code> can be eliminated by modifying the source code to explicitly test for null before calling the <a class=\"xref\" href=\"system.object#System_Object_Equals_\" data-linktype=\"relative-path\">Equals</a> override and then re-compiling. The following example contains the corrected source code that handles a <code>null</code> argument.  </p>\n<pre><code class=\"lang-vb\" name=\"System.Exception.Class#5\">Public Class Person\n   Private _name As String\n   \n   Public Property Name As String\n      Get\n         Return _name\n      End Get\n      Set\n         _name = value\n      End Set\n   End Property\n   \n   Public Overrides Function Equals(obj As Object) As Boolean\n      &#39; This implementation handles a null obj argument.\n      Dim p As Person = TryCast(obj, Person)\n      If p Is Nothing Then \n         Return False\n      Else\n         Return Me.Name.Equals(p.Name)\n      End If\n   End Function\nEnd Class\n\nModule Example\n   Public Sub Main()\n      Dim p1 As New Person()\n      p1.Name = &quot;John&quot;\n      Dim p2 As Person = Nothing\n      \n      Console.WriteLine(&quot;p1 = p2: {0}&quot;, p1.Equals(p2))   \n   End Sub\nEnd Module\n&#39; The example displays the following output:\n&#39;       p1 = p2: False\n</code></pre><pre><code class=\"lang-cs\" name=\"System.Exception.Class#5\">using System;\n\npublic class Person\n{\n   private string _name;\n   \n   public string Name \n   {\n      get { return _name; } \n      set { _name = value; }\n   }\n   \n   public override int GetHashCode()\n   {\n      return this.Name.GetHashCode();  \n   }  \n                        \n   public override bool Equals(object obj)\n   {\n       // This implementation handles a null obj argument.\n       Person p = obj as Person; \n       if (p == null) \n          return false;\n       else\n          return this.Name.Equals(p.Name);\n   }\n}\n\npublic class Example\n{\n   public static void Main()\n   {\n      Person p1 = new Person();\n      p1.Name = &quot;John&quot;;\n      Person p2 = null; \n      \n      Console.WriteLine(&quot;p1 = p2: {0}&quot;, p1.Equals(p2));   \n   }\n}\n// The example displays the following output:\n//        p1 = p2: False\n</code></pre><p> Instead of using exception handling for usage errors, you can use the <a class=\"xref\" href=\"system.diagnostics.debug#System_Diagnostics_Debug_Assert_\" data-linktype=\"relative-path\">Assert</a> method to identify usage errors in debug builds, and the <a class=\"xref\" href=\"system.diagnostics.trace#System_Diagnostics_Trace_Assert_\" data-linktype=\"relative-path\">Assert</a> method to identify usage errors in both debug and release builds. For more information, see <a href=\"../Topic/Assertions%20in%20Managed%20Code.md\" data-linktype=\"relative-path\">Assertions in Managed Code</a>.  </p>\n</li>\n<li><p><strong>Program errors.</strong> A program error is a run-time error that cannot necessarily be avoided by writing bug-free code.  </p>\n<p> In some cases, a program error may reflect an expected or routine error condition. In this case, you may want to avoid using exception handling to deal with the program error and instead retry the operation. For example, if the user is expected to input a date in a particular format, you can parse the date string by calling the <a class=\"xref\" href=\"system.datetime#System_DateTime_TryParseExact_\" data-linktype=\"relative-path\">TryParseExact</a> method, which returns a <a class=\"xref\" href=\"system.boolean\" data-linktype=\"relative-path\">Boolean</a> value that indicates whether the parse operation succeeded, instead of using the <a class=\"xref\" href=\"system.datetime#System_DateTime_ParseExact_\" data-linktype=\"relative-path\">ParseExact</a> method, which throws a <a class=\"xref\" href=\"system.formatexception\" data-linktype=\"relative-path\">FormatException</a> exception if the date string cannot be converted to a <a class=\"xref\" href=\"system.datetime\" data-linktype=\"relative-path\">DateTime</a> value. Similarly, if a user tries to open a file that does not exist, you can first call the <a class=\"xref\" href=\"system.io.file#System_IO_File_Exists_\" data-linktype=\"relative-path\">Exists</a> method to check whether the file exists and, if it does not, prompt the user whether he or she wants to create it.  </p>\n<p> In other cases, a program error reflects an unexpected error condition that can be handled in your code. For example, even if you&#39;ve checked to ensure that a file exists, it may be deleted before you can open it, or it may be corrupted. In that case, trying to open the file by instantiating a <a class=\"xref\" href=\"system.io.streamreader\" data-linktype=\"relative-path\">StreamReader</a> object or calling the <a class=\"xref\" href=\"system.io.file#System_IO_File_Open_\" data-linktype=\"relative-path\">Open</a> method may throw a <a class=\"xref\" href=\"system.io.filenotfoundexception\" data-linktype=\"relative-path\">FileNotFoundException</a> exception. In these cases, you should use exception handling to recover from the error.  </p>\n</li>\n<li><p><strong>System failures.</strong> A system failure is a run-time error that cannot be handled programmatically in a meaningful way. For example, any method can throw an <a class=\"xref\" href=\"system.outofmemoryexception\" data-linktype=\"relative-path\">OutOfMemoryException</a> exception if the common language runtime is unable to allocate additional memory. Ordinarily, system failures are not handled by using exception handling. Instead, you may be able to use an event such as <a class=\"xref\" href=\"system.appdomain#System_AppDomain_UnhandledException\" data-linktype=\"relative-path\">System.AppDomain.UnhandledException</a> and call the <a class=\"xref\" href=\"system.environment#System_Environment_FailFast_\" data-linktype=\"relative-path\">FailFast</a> method to log exception information and notify the user of the failure before the application terminates.  </p>\n</li>\n</ul>\n<p><a name=\"TryCatch\"></a>   </p>\n<h2 id=\"trycatch-blocks\">Try/catch blocks</h2>\n<p> The common language runtime provides an exception handling model that is based on the representation of exceptions as objects, and the separation of program code and exception handling code into <code>try</code> blocks and <code>catch</code> blocks. There can be one or more <code>catch</code> blocks, each designed to handle a particular type of exception, or one block designed to catch a more specific exception than another block.  </p>\n<p> If an application handles exceptions that occur during the execution of a block of application code, the code must be placed within a <code>try</code> statement and is called a <code>try</code> block. Application code that handles exceptions thrown by a <code>try</code> block is placed within a <code>catch</code> statement and is called a <code>catch</code> block. Zero or more <code>catch</code> blocks are associated with a <code>try</code> block, and each <code>catch</code> block includes a type filter that determines the types of exceptions it handles.  </p>\n<p> When an exception occurs in a <code>try</code> block, the system searches the associated <code>catch</code> blocks in the order they appear in application code, until it locates a <code>catch</code> block that handles the exception. A <code>catch</code> block handles an exception of type <code>T</code> if the type filter of the catch block specifies <code>T</code> or any type that <code>T</code> derives from. The system stops searching after it finds the first <code>catch</code> block that handles the exception. For this reason, in application code, a <code>catch</code> block that handles a type must be specified before a <code>catch</code> block that handles its base types, as demonstrated in the example that follows this section. A catch block that handles <code>System.Exception</code> is specified last.  </p>\n<p> If none of the <code>catch</code> blocks associated with the current <code>try</code> block handle the exception, and the current <code>try</code> block is nested within other <code>try</code> blocks in the current call, the <code>catch</code> blocks associated with the next enclosing <code>try</code> block are searched. If no <code>catch</code> block for the exception is found, the system searches previous nesting levels in the current call. If no <code>catch</code> block for the exception is found in the current call, the exception is passed up the call stack, and the previous stack frame is searched for a <code>catch</code> block that handles the exception. The search of the call stack continues until the exception is handled or until no more frames exist on the call stack. If the top of the call stack is reached without finding a <code>catch</code> block that handles the exception, the default exception handler handles it and the application terminates.  </p>\n<p><a name=\"Features\"></a>   </p>\n<h2 id=\"exception-type-features\">Exception type features</h2>\n<p> Exception types support the following features:  </p>\n<ul>\n<li><p>Human-readable text that describes the error. When an exception occurs, the runtime makes a text message available to inform the user of the nature of the error and to suggest action to resolve the problem. This text message is held in the <a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a> property of the exception object. During the creation of the exception object, you can pass a text string to the constructor to describe the details of that particular exception. If no error message argument is supplied to the constructor, the default error message is used. For more information, see the <a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a> property.  </p>\n</li>\n<li><p>The state of the call stack when the exception was thrown. The <a class=\"xref\" href=\"system.exception#System_Exception_StackTrace_\" data-linktype=\"relative-path\">StackTrace</a> property carries a stack trace that can be used to determine where the error occurs in the code. The stack trace lists all the called methods and the line numbers in the source file where the calls are made.  </p>\n</li>\n</ul>\n<p><a name=\"Properties\"></a>   </p>\n<h2 id=\"exception-class-properties\">Exception class properties</h2>\n<p> The Exception class includes a number of properties that help identify the code location, the type, the help file, and the reason for the exception: <a class=\"xref\" href=\"system.exception#System_Exception_StackTrace_\" data-linktype=\"relative-path\">StackTrace</a>, <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a>, <a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a>, <a class=\"xref\" href=\"system.exception#System_Exception_HelpLink_\" data-linktype=\"relative-path\">HelpLink</a>, <a class=\"xref\" href=\"system.exception#System_Exception_HResult_\" data-linktype=\"relative-path\">HResult</a>, <a class=\"xref\" href=\"system.exception#System_Exception_Source_\" data-linktype=\"relative-path\">Source</a>, <a class=\"xref\" href=\"system.exception#System_Exception_TargetSite_\" data-linktype=\"relative-path\">TargetSite</a>, and <a class=\"xref\" href=\"system.exception#System_Exception_Data_\" data-linktype=\"relative-path\">Data</a>.  </p>\n<p> When a causal relationship exists between two or more exceptions, the <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property maintains this information. The outer exception is thrown in response to this inner exception. The code that handles the outer exception can use the information from the earlier inner exception to handle the error more appropriately. Supplementary information about the exception can be stored as a collection of key/value pairs in the <a class=\"xref\" href=\"system.exception#System_Exception_Data_\" data-linktype=\"relative-path\">Data</a> property.  </p>\n<p> The error message string that is passed to the constructor during the creation of the exception object should be localized and can be supplied from a resource file by using the <a class=\"xref\" href=\"system.resources.resourcemanager\" data-linktype=\"relative-path\">ResourceManager</a> class. For more information about localized resources, see the <a href=\"../Topic/Creating%20Satellite%20Assemblies%20for%20Desktop%20Apps.md\" data-linktype=\"relative-path\">Creating Satellite Assemblies</a> and <a href=\"../Topic/Packaging%20and%20Deploying%20Resources%20in%20Desktop%20Apps.md\" data-linktype=\"relative-path\">Packaging and Deploying Resources</a> topics.  </p>\n<p> To provide the user with extensive information about why the exception occurred, the <a class=\"xref\" href=\"system.exception#System_Exception_HelpLink_\" data-linktype=\"relative-path\">HelpLink</a> property can hold a URL (or URN) to a help file.  </p>\n<p> The Exception class uses the HRESULT COR_E_EXCEPTION, which has the value 0x80131500.  </p>\n<p> For a list of initial property values for an instance of the Exception class, see the <a class=\"xref\" href=\"system.exception#System_Exception__ctor_\" data-linktype=\"relative-path\">Exception</a> constructors.  </p>\n<p><a name=\"Performance\"></a>   </p>\n<h2 id=\"performance-considerations\">Performance considerations</h2>\n<p> Throwing or handling an exception consumes a significant amount of system resources and execution time. Throw exceptions only to handle truly extraordinary conditions, not to handle predictable events or flow control. For example, in some cases, such as when you&#39;re developing a class library, it&#39;s reasonable to throw an exception if a method argument is invalid, because you expect your method to be called with valid parameters. An invalid method argument, if it is not the result of a usage error, means that something extraordinary has occurred. Conversely, do not throw an exception if user input is invalid, because you can expect users to occasionally enter invalid data. Instead, provide a retry mechanism so users can enter valid input. Nor should you use exceptions to handle usage errors. Instead, use <a href=\"../Topic/Assertions%20in%20Managed%20Code.md\" data-linktype=\"relative-path\">assertions</a> to identify and correct usage errors.  </p>\n<p> In addition, do not throw an exception when a return code is sufficient; do not convert a return code to an exception; and do not routinely catch an exception, ignore it, and then continue processing.  </p>\n<p><a name=\"Rethrow\"></a>   </p>\n<h2 id=\"re-throwing-an-exception\">Re-throwing an exception</h2>\n<p> In many cases, an exception handler simply wants to pass the exception on to the caller. This most often occurs in:  </p>\n<ul>\n<li><p>A class library that in turn wraps calls to methods in the .NET Framework class library or other class libraries.  </p>\n</li>\n<li><p>An application or library that encounters a fatal exception. The exception handler can log the exception and then re-throw the exception.  </p>\n<p>The recommended way to re-throw an exception is to simply use the <a href=\"../Topic/throw%20(C%23%20Reference).md\" data-linktype=\"relative-path\">throw</a> statement in C# and the <a href=\"../Topic/Throw%20Statement%20(Visual%20Basic).md\" data-linktype=\"relative-path\">Throw</a> statement in Visual Basic without including an expression. This ensures that all call stack information is preserved when the exception is propagated to the caller. The following example illustrates this. A string extension method, <code>FindOccurrences</code>, wraps one or more calls to <a class=\"xref\" href=\"system.string#System_String_IndexOf_System_String_System_Int32_\" data-linktype=\"relative-path\">System.String.IndexOf(String,Int32)</a> without validating its arguments beforehand.  </p>\n<pre><code class=\"lang-vb\" name=\"System.Exception.Class#6\">Imports System.Collections.Generic\nImports System.Runtime.CompilerServices\n\nPublic Module Library\n   &lt;Extension()&gt;\n   Public Function FindOccurrences(s As String, f As String) As Integer()\n      Dim indexes As New List(Of Integer)\n      Dim currentIndex As Integer = 0\n      Try\n         Do While currentIndex &gt;= 0 And currentIndex &lt; s.Length\n            currentIndex = s.IndexOf(f, currentIndex)\n            If currentIndex &gt;= 0 Then\n               indexes.Add(currentIndex)\n               currentIndex += 1\n            End If\n         Loop\n      Catch e As ArgumentNullException\n         &#39; Perform some action here, such as logging this exception.\n         \n         Throw\n      End Try\n      Return indexes.ToArray()\n   End Function\nEnd Module\n</code></pre><pre><code class=\"lang-cs\" name=\"System.Exception.Class#6\">using System;\nusing System.Collections.Generic;\nusing System.Runtime.CompilerServices;\n\npublic static class Library\n{\n   public static int[] FindOccurrences(this String s, String f)\n   {\n      var indexes = new List&lt;int&gt;();\n      int currentIndex = 0;\n      try {\n         while (currentIndex &gt;= 0 &amp;&amp; currentIndex &lt; s.Length) {\n            currentIndex = s.IndexOf(f, currentIndex);\n            if (currentIndex &gt;= 0) {\n               indexes.Add(currentIndex);\n               currentIndex++;\n            }\n         }\n      }\n      catch (ArgumentNullException e) {\n         // Perform some action here, such as logging this exception.\n\n         throw;\n      }\n      return indexes.ToArray();\n   }\n}\n</code></pre><p>A caller then calls <code>FindOccurrences</code> twice. In the second call to <code>FindOccurrences</code>, the caller passes a <code>null</code> as the search string, which cases the <a class=\"xref\" href=\"system.string#System_String_IndexOf_System_String_System_Int32_\" data-linktype=\"relative-path\">System.String.IndexOf(String,Int32)</a> method to throw an <a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a> exception. This exception is handled by the <code>FindOccurrences</code> method and passed back to the caller. Because the throw statement is used with no expression, the output from the example shows that the call stack is preserved.  </p>\n<pre><code class=\"lang-vb\" name=\"System.Exception.Class#7\">Module Example\n   Public Sub Main()\n      Dim s As String = &quot;It was a cold day when...&quot;\n      Dim indexes() As Integer = s.FindOccurrences(&quot;a&quot;)\n      ShowOccurrences(s, &quot;a&quot;, indexes)\n      Console.WriteLine()\n\n      Dim toFind As String = Nothing\n      Try\n         indexes = s.FindOccurrences(toFind)\n         ShowOccurrences(s, toFind, indexes)\n      Catch e As ArgumentNullException\n         Console.WriteLine(&quot;An exception ({0}) occurred.&quot;,\n                           e.GetType().Name)\n         Console.WriteLine(&quot;Message:{0}   {1}{0}&quot;, vbCrLf, e.Message)\n         Console.WriteLine(&quot;Stack Trace:{0}   {1}{0}&quot;, vbCrLf, e.StackTrace)\n      End Try\n   End Sub\n   \n   Private Sub ShowOccurrences(s As String, toFind As String, indexes As Integer())\n      Console.Write(&quot;&#39;{0}&#39; occurs at the following character positions: &quot;,\n                    toFind)\n      For ctr As Integer = 0 To indexes.Length - 1\n         Console.Write(&quot;{0}{1}&quot;, indexes(ctr),\n                       If(ctr = indexes.Length - 1, &quot;&quot;, &quot;, &quot;))\n      Next\n      Console.WriteLine()\n   End Sub\nEnd Module\n&#39; The example displays the following output:\n&#39;    &#39;a&#39; occurs at the following character positions: 4, 7, 15\n&#39;\n&#39;    An exception (ArgumentNullException) occurred.\n&#39;    Message:\n&#39;       Value cannot be null.\n&#39;    Parameter name: value\n&#39;\n&#39;    Stack Trace:\n&#39;          at System.String.IndexOf(String value, Int32 startIndex, Int32 count, Stri\n&#39;    ngComparison comparisonType)\n&#39;       at Library.FindOccurrences(String s, String f)\n&#39;       at Example.Main()\n</code></pre><pre><code class=\"lang-cs\" name=\"System.Exception.Class#7\">public class Example\n{\n   public static void Main()\n   {\n      String s = &quot;It was a cold day when...&quot;;\n      int[] indexes = s.FindOccurrences(&quot;a&quot;);\n      ShowOccurrences(s, &quot;a&quot;, indexes);\n      Console.WriteLine();\n      \n      String toFind = null;\n      try {\n         indexes = s.FindOccurrences(toFind);\n         ShowOccurrences(s, toFind, indexes);\n      }\n      catch (ArgumentNullException e) {\n         Console.WriteLine(&quot;An exception ({0}) occurred.&quot;,\n                           e.GetType().Name);\n         Console.WriteLine(&quot;Message:\\n   {0}\\n&quot;, e.Message);\n         Console.WriteLine(&quot;Stack Trace:\\n   {0}\\n&quot;, e.StackTrace);\n      }\n   }\n\n   private static void ShowOccurrences(String s, String toFind, int[] indexes)\n   {\n      Console.Write(&quot;&#39;{0}&#39; occurs at the following character positions: &quot;,\n                    toFind);\n      for (int ctr = 0; ctr &lt; indexes.Length; ctr++)\n         Console.Write(&quot;{0}{1}&quot;, indexes[ctr],\n                       ctr == indexes.Length - 1 ? &quot;&quot; : &quot;, &quot;);\n\n      Console.WriteLine();\n   }\n}\n// The example displays the following output:\n//    &#39;a&#39; occurs at the following character positions: 4, 7, 15\n//\n//    An exception (ArgumentNullException) occurred.\n//    Message:\n//       Value cannot be null.\n//    Parameter name: value\n//\n//    Stack Trace:\n//          at System.String.IndexOf(String value, Int32 startIndex, Int32 count, Stri\n//    ngComparison comparisonType)\n//       at Library.FindOccurrences(String s, String f)\n//       at Example.Main()\n</code></pre><p>In contrast, if the exception is re-thrown by using the  </p>\n</li>\n</ul>\n<pre><code class=\"lang-c#\">throw e  \n</code></pre><pre><code class=\"lang-vb\">Throw e  \n</code></pre><p> statement, the full call stack is not preserved, and the example would generate the following output:  </p>\n<pre><code class=\"lang-Output\">\n&#39;a&#39; occurs at the following character positions: 4, 7, 15  \n\nAn exception (ArgumentNullException) occurred.  \nMessage:  \n   Value cannot be null.  \nParameter name: value  \n\nStack Trace:  \n      at Library.FindOccurrences(String s, String f)  \n   at Example.Main()  \n</code></pre><p> A slightly more cumbersome alternative is to throw a new exception, and to preserve the original exception&#39;s call stack information in an inner exception. The caller can then use the new exception&#39;s <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property to retrieve stack frame and other information about the original exception. In this case, the throw statement is:  </p>\n<pre><code class=\"lang-vb\" name=\"System.Exception.Class#8\">Throw New ArgumentNullException(&quot;You must supply a search string.&quot;,\n                                e)\n</code></pre><pre><code class=\"lang-cs\" name=\"System.Exception.Class#8\">throw new ArgumentNullException(&quot;You must supply a search string.&quot;,\n                                e);\n</code></pre><p> The user code that handles the exception has to know that the <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property contains information about the original exception, as the following exception handler illustrates.  </p>\n<pre><code class=\"lang-vb\" name=\"System.Exception.Class#9\">Try\n   indexes = s.FindOccurrences(toFind)\n   ShowOccurrences(s, toFind, indexes)\nCatch e As ArgumentNullException\n   Console.WriteLine(&quot;An exception ({0}) occurred.&quot;,\n                     e.GetType().Name)\n   Console.WriteLine(&quot;   Message: {1}{0}&quot;, vbCrLf, e.Message)\n   Console.WriteLine(&quot;   Stack Trace:{0}   {1}{0}&quot;, vbCrLf, e.StackTrace)\n   Dim ie As Exception = e.InnerException\n   If ie IsNot Nothing Then\n      Console.WriteLine(&quot;   The Inner Exception:&quot;)\n      Console.WriteLine(&quot;      Exception Name: {0}&quot;, ie.GetType().Name)\n      Console.WriteLine(&quot;      Message: {1}{0}&quot;, vbCrLf, ie.Message)\n      Console.WriteLine(&quot;      Stack Trace:{0}   {1}{0}&quot;, vbCrLf, ie.StackTrace)\n   End If\nEnd Try\n&#39; The example displays the following output:\n&#39;       &#39;a&#39; occurs at the following character positions: 4, 7, 15\n&#39;\n&#39;       An exception (ArgumentNullException) occurred.\n&#39;          Message: You must supply a search string.\n&#39;\n&#39;          Stack Trace:\n&#39;             at Library.FindOccurrences(String s, String f)\n&#39;          at Example.Main()\n&#39;\n&#39;          The Inner Exception:\n&#39;             Exception Name: ArgumentNullException\n&#39;             Message: Value cannot be null.\n&#39;       Parameter name: value\n&#39;\n&#39;             Stack Trace:\n&#39;             at System.String.IndexOf(String value, Int32 startIndex, Int32 count, Stri\n&#39;       ngComparison comparisonType)\n&#39;          at Library.FindOccurrences(String s, String f)\n</code></pre><pre><code class=\"lang-cs\" name=\"System.Exception.Class#9\">try {\n   indexes = s.FindOccurrences(toFind);\n   ShowOccurrences(s, toFind, indexes);\n}\ncatch (ArgumentNullException e) {\n   Console.WriteLine(&quot;An exception ({0}) occurred.&quot;,\n                     e.GetType().Name);\n   Console.WriteLine(&quot;   Message:\\n{0}&quot;, e.Message);\n   Console.WriteLine(&quot;   Stack Trace:\\n   {0}&quot;, e.StackTrace);\n   Exception ie = e.InnerException;\n   if (ie != null) {\n      Console.WriteLine(&quot;   The Inner Exception:&quot;);\n      Console.WriteLine(&quot;      Exception Name: {0}&quot;, ie.GetType().Name);\n      Console.WriteLine(&quot;      Message: {0}\\n&quot;, ie.Message);\n      Console.WriteLine(&quot;      Stack Trace:\\n   {0}\\n&quot;, ie.StackTrace);\n   }\n}\n// The example displays the following output:\n//    &#39;a&#39; occurs at the following character positions: 4, 7, 15\n//\n//    An exception (ArgumentNullException) occurred.\n//       Message: You must supply a search string.\n//\n//       Stack Trace:\n//          at Library.FindOccurrences(String s, String f)\n//       at Example.Main()\n//\n//       The Inner Exception:\n//          Exception Name: ArgumentNullException\n//          Message: Value cannot be null.\n//    Parameter name: value\n//\n//          Stack Trace:\n//          at System.String.IndexOf(String value, Int32 startIndex, Int32 count, Stri\n//    ngComparison comparisonType)\n//       at Library.FindOccurrences(String s, String f)\n</code></pre><p><a name=\"Standard\"></a>   </p>\n<h2 id=\"choosing-standard-exceptions\">Choosing standard exceptions</h2>\n<p> When you have to throw an exception, you can often use an existing exception type in the .NET Framework instead of implementing a custom exception. You should use a standard exception type under these two conditions:  </p>\n<ul>\n<li><p>You are throwing an exception that is caused by a usage error (that is, by an error in program logic made by the developer who is calling your method). Typically, you would throw an exception such as <a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a>, <a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a>, <a class=\"xref\" href=\"system.invalidoperationexception\" data-linktype=\"relative-path\">InvalidOperationException</a>, or <a class=\"xref\" href=\"system.notsupportedexception\" data-linktype=\"relative-path\">NotSupportedException</a>. The string you supply to the exception object&#39;s constructor when instantiating the exception object should describe the error so that the developer can fix it. For more information, see the <a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a> property.  </p>\n</li>\n<li><p>You are handling an error that can be communicated to the caller with an existing .NET Framework exception. You should throw the most derived exception possible. For example, if a method requires an argument to be a valid member of an enumeration type, you should throw an <a class=\"xref\" href=\"system.componentmodel.invalidenumargumentexception\" data-linktype=\"relative-path\">InvalidEnumArgumentException</a> (the most derived class) rather than an <a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a>.  </p>\n<p>The following table lists common exception types and the conditions under which you would throw them.  </p>\n</li>\n</ul>\n<table>\n<thead>\n<tr>\n<th>Exception</th>\n<th>Condition</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a></td>\n<td>A non-null argument that is passed to a method is invalid.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></td>\n<td>An argument that is passed to a method is <code>null</code>.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.argumentoutofrangeexception\" data-linktype=\"relative-path\">ArgumentOutOfRangeException</a></td>\n<td>An argument is outside the range of valid values.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.io.directorynotfoundexception\" data-linktype=\"relative-path\">DirectoryNotFoundException</a></td>\n<td>Part of a directory path is not valid.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.dividebyzeroexception\" data-linktype=\"relative-path\">DivideByZeroException</a></td>\n<td>The denominator in an integer or <a class=\"xref\" href=\"system.decimal\" data-linktype=\"relative-path\">Decimal</a> division operation is zero.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.io.drivenotfoundexception\" data-linktype=\"relative-path\">DriveNotFoundException</a></td>\n<td>A drive is unavailable or does not exist.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.io.filenotfoundexception\" data-linktype=\"relative-path\">FileNotFoundException</a></td>\n<td>A file does not exist.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.formatexception\" data-linktype=\"relative-path\">FormatException</a></td>\n<td>A value is not in an appropriate format to be converted from a string by a conversion method such as <code>Parse</code>.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.indexoutofrangeexception\" data-linktype=\"relative-path\">IndexOutOfRangeException</a></td>\n<td>An index is outside the bounds of an array or collection.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.invalidoperationexception\" data-linktype=\"relative-path\">InvalidOperationException</a></td>\n<td>A method call is invalid in an object&#39;s current state.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.collections.generic.keynotfoundexception\" data-linktype=\"relative-path\">KeyNotFoundException</a></td>\n<td>The specified key for accessing a member in a collection cannot be found.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.notimplementedexception\" data-linktype=\"relative-path\">NotImplementedException</a></td>\n<td>A method or operation is not implemented.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.notsupportedexception\" data-linktype=\"relative-path\">NotSupportedException</a></td>\n<td>A method or operation is not supported.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.objectdisposedexception\" data-linktype=\"relative-path\">ObjectDisposedException</a></td>\n<td>An operation is performed on an object that has been disposed.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.overflowexception\" data-linktype=\"relative-path\">OverflowException</a></td>\n<td>An arithmetic, casting, or conversion operation results in an overflow.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.io.pathtoolongexception\" data-linktype=\"relative-path\">PathTooLongException</a></td>\n<td>A path or file name exceeds the maximum system-defined length.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.platformnotsupportedexception\" data-linktype=\"relative-path\">PlatformNotSupportedException</a></td>\n<td>The operation is not supported on the current platform.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.rankexception\" data-linktype=\"relative-path\">RankException</a></td>\n<td>An array with the wrong number of dimensions is passed to a method.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.timeoutexception\" data-linktype=\"relative-path\">TimeoutException</a></td>\n<td>The time interval allotted to an operation has expired.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.uriformatexception\" data-linktype=\"relative-path\">UriFormatException</a></td>\n<td>An invalid Uniform Resource Identifier (URI) is used.</td>\n</tr>\n</tbody>\n</table>\n<p><a name=\"Custom\"></a>   </p>\n<h2 id=\"implementing-custom-exceptions\">Implementing custom exceptions</h2>\n<p> In the following cases, using an existing .NET Framework exception to handle an error condition is not adequate:  </p>\n<ul>\n<li><p>When the exception reflects a unique program error that cannot be mapped to an existing .NET Framework exception.  </p>\n</li>\n<li><p>When the exception requires handling that is different from the handling that is appropriate for an existing .NET Framework exception, or the exception must be disambiguated from a similar exception. For example, if you throw an <a class=\"xref\" href=\"system.argumentoutofrangeexception\" data-linktype=\"relative-path\">ArgumentOutOfRangeException</a> exception when parsing the numeric representation of a string that is out of range of the target integral type, you would not want to use the same exception for an error that results from the caller not supplying the appropriate constrained values when calling the method.  </p>\n<p>The Exception class is the base class of all exceptions in the .NET Framework. Many derived classes rely on the inherited behavior of the members of the Exception class; they do not override the members of Exception, nor do they define any unique members.  </p>\n<p>To define your own exception class:  </p>\n</li>\n</ul>\n<ol>\n<li><p>Define a class that inherits from Exception. If necessary, define any unique members needed by your class to provide additional information about the exception. For example, the <a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a> class includes a <a class=\"xref\" href=\"system.argumentexception#System_ArgumentException_ParamName_\" data-linktype=\"relative-path\">ParamName</a> property that specifies the name of the parameter whose argument caused the exception, and the <a class=\"xref\" href=\"system.text.regularexpressions.regexmatchtimeoutexception\" data-linktype=\"relative-path\">RegexMatchTimeoutException</a> property includes a <a class=\"xref\" href=\"system.text.regularexpressions.regexmatchtimeoutexception#System_Text_RegularExpressions_RegexMatchTimeoutException_MatchTimeout_\" data-linktype=\"relative-path\">MatchTimeout</a> property that indicates the time-out interval.  </p>\n</li>\n<li><p>If necessary, override any inherited members whose functionality you want to change or modify. Note that most existing derived classes of Exception do not override the behavior of inherited members.  </p>\n</li>\n<li><p>Determine whether your custom exception object is serializable. Serialization enables you to save information about the exception and permits exception information to be shared by a server and a client proxy in a remoting context. To make the exception object serializable, mark it with the <a class=\"xref\" href=\"system.serializableattribute\" data-linktype=\"relative-path\">SerializableAttribute</a> attribute.  </p>\n</li>\n<li><p>Define the constructors of your exception class. Typically, exception classes have one or more of the following constructors:  </p>\n<ul>\n<li><p><a class=\"xref\" href=\"system.exception#System_Exception__ctor\" data-linktype=\"relative-path\">Exception()</a>, which uses default values to initialize the properties of a new exception object.  </p>\n</li>\n<li><p><a class=\"xref\" href=\"system.exception#System_Exception__ctor_System_String_\" data-linktype=\"relative-path\">Exception(String)</a>, which initializes a new exception object with a specified error message.  </p>\n</li>\n<li><p><a class=\"xref\" href=\"system.exception#System_Exception__ctor_System_String_System_Exception_\" data-linktype=\"relative-path\">Exception(String,Exception)</a>, which initializes a new exception object with a specified error message and inner exception.  </p>\n</li>\n<li><p><a class=\"xref\" href=\"system.exception#System_Exception__ctor_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\" data-linktype=\"relative-path\">Exception(SerializationInfo,StreamingContext)</a>, which is a <code>protected</code> constructor that initializes a new exception object from serialized data. You should implement this constructor if you&#39;ve chosen to make your exception object serializable.  </p>\n</li>\n</ul>\n<p>The following example illustrates the use of a custom exception class. It defines a <code>NotPrimeException</code> exception that is thrown when a client tries to retrieve a sequence of prime numbers by specifying a starting number that is not prime. The exception defines a new property, <code>NonPrime</code>, that returns the non-prime number that caused the exception. Besides implementing a protected parameterless constructor and a constructor with <a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a> and <a class=\"xref\" href=\"system.runtime.serialization.streamingcontext\" data-linktype=\"relative-path\">StreamingContext</a> parameters for serialization, the <code>NotPrimeException</code> class defines three additional constructors to support the <code>NonPrime</code> property.  Each constructor calls a base class constructor in addition to preserving the value of the non-prime number. The <code>NotPrimeException</code> class is also marked with the <a class=\"xref\" href=\"system.serializableattribute\" data-linktype=\"relative-path\">SerializableAttribute</a> attribute.  </p>\n<pre><code class=\"lang-cs\" name=\"System.Exception.Class#1\">using System;\nusing System.Runtime.Serialization;\n\n[Serializable()]\npublic class NotPrimeException : Exception\n{\n   private int notAPrime;\n\n   protected NotPrimeException()\n      : base()\n   { }\n\n   public NotPrimeException(int value) :\n      base(String.Format(&quot;{0} is not a prime number.&quot;, value))\n   {\n      notAPrime = value;\n   }\n\n   public NotPrimeException(int value, string message)\n      : base(message)\n   {\n      notAPrime = value;\n   }\n\n   public NotPrimeException(int value, string message, Exception innerException) :\n      base(message, innerException)\n   {\n      notAPrime = value;\n   }\n\n   protected NotPrimeException(SerializationInfo info,\n                               StreamingContext context)\n      : base(info, context)\n   { }\n\n   public int NonPrime\n   { get { return notAPrime; } }\n}\n</code></pre><pre><code class=\"lang-vb\" name=\"System.Exception.Class#1\">Imports System.Runtime.Serialization\n\n&lt;Serializable()&gt; _\nPublic Class NotPrimeException : Inherits Exception\n   Private notAPrime As Integer\n\n   Protected Sub New()\n      MyBase.New()\n   End Sub\n\n   Public Sub New(value As Integer)\n      MyBase.New(String.Format(&quot;{0} is not a prime number.&quot;, value))\n      notAPrime = value\n   End Sub\n\n   Public Sub New(value As Integer, message As String)\n      MyBase.New(message)\n      notAPrime = value\n   End Sub\n\n   Public Sub New(value As Integer, message As String, innerException As Exception)\n      MyBase.New(message, innerException)\n      notAPrime = value\n   End Sub\n\n   Protected Sub New(info As SerializationInfo,\n                     context As StreamingContext)\n      MyBase.New(info, context)\n   End Sub\n\n   Public ReadOnly Property NonPrime As Integer\n      Get\n         Return notAPrime\n      End Get\n   End Property\nEnd Class\n</code></pre><p>The <code>PrimeNumberGenerator</code> class shown in the following example uses the Sieve of Eratosthenes to calculate the sequence of prime numbers from 2 to a limit specified by the client in the call to its class constructor. The <code>GetPrimesFrom</code> method returns all prime numbers that are greater than or equal to a specified lower limit, but throws a <code>NotPrimeException</code> if that lower limit is not a prime number.  </p>\n<pre><code class=\"lang-vb\" name=\"System.Exception.Class#2\">Imports System.Collections.Generic\n\n&lt;Serializable()&gt; Public Class PrimeNumberGenerator\n   Private Const START As Integer = 2\n   Private maxUpperBound As Integer = 10000000\n   Private upperBound As Integer\n   Private primeTable() As Boolean\n   Private primes As New List(Of Integer)\n\n   Public Sub New(upperBound As Integer)\n      If upperBound &gt; maxUpperBound Then\n         Dim message As String = String.Format(\n             &quot;{0} exceeds the maximum upper bound of {1}.&quot;,\n             upperBound, maxUpperBound)\n         Throw New ArgumentOutOfRangeException(message)\n      End If\n      Me.upperBound = upperBound\n      &#39; Create array and mark 0, 1 as not prime (True).\n      ReDim primeTable(upperBound)\n      primeTable(0) = True\n      primeTable(1) = True\n\n      &#39; Use Sieve of Eratosthenes to determine prime numbers.\n      For ctr As Integer = START To CInt(Math.Ceiling(Math.Sqrt(upperBound)))\n         If primeTable(ctr) Then Continue For\n\n         For multiplier As Integer = ctr To CInt(upperBound \\ ctr)\n            If ctr * multiplier &lt;= upperBound Then primeTable(ctr * multiplier) = True\n         Next\n      Next\n      &#39; Populate array with prime number information.\n      Dim index As Integer = START\n      Do While index &lt;&gt; -1\n         index = Array.FindIndex(primeTable, index, Function(flag)\n                                                       Return Not flag\n                                                    End Function)\n         If index &gt;= 1 Then\n            primes.Add(index)\n            index += 1\n         End If\n      Loop\n   End Sub\n\n   Public Function GetAllPrimes() As Integer()\n      Return primes.ToArray()\n   End Function\n\n   Public Function GetPrimesFrom(prime As Integer) As Integer()\n      Dim start As Integer = primes.FindIndex(Function(value)\n                                                 Return value = prime\n                                              End Function)\n      If start &lt; 0 Then\n         Throw New NotPrimeException(prime, String.Format(&quot;{0} is not a prime number.&quot;, prime))\n      Else\n         Return primes.FindAll(Function(value)\n                                  Return value &gt;= prime\n                               End Function).ToArray()\n      End If\n   End Function\nEnd Class\n</code></pre><pre><code class=\"lang-cs\" name=\"System.Exception.Class#2\">using System;\nusing System.Collections.Generic;\n\n\n[Serializable]\npublic class PrimeNumberGenerator\n{\n   private const int START = 2;\n   private int maxUpperBound = 10000000;\n   private int upperBound;\n   private bool[] primeTable;\n   private List&lt;int&gt; primes = new List&lt;int&gt;();\n\n   public PrimeNumberGenerator(int upperBound)\n   {\n      if (upperBound &gt; maxUpperBound)\n      {\n         string message = String.Format(\n                           &quot;{0} exceeds the maximum upper bound of {1}.&quot;,\n                           upperBound, maxUpperBound);\n         throw new ArgumentOutOfRangeException(message);\n      }\n      this.upperBound = upperBound;\n      // Create array and mark 0, 1 as not prime (True).\n      primeTable = new bool[upperBound + 1];\n      primeTable[0] = true;\n      primeTable[1] = true;\n\n      // Use Sieve of Eratosthenes to determine prime numbers.\n      for (int ctr = START; ctr &lt;= (int)Math.Ceiling(Math.Sqrt(upperBound));\n            ctr++)\n      {\n         if (primeTable[ctr]) continue;\n\n         for (int multiplier = ctr; multiplier &lt;= upperBound / ctr; multiplier++)\n            if (ctr * multiplier &lt;= upperBound) primeTable[ctr * multiplier] = true;\n      }\n      // Populate array with prime number information.\n      int index = START;\n      while (index != -1)\n      {\n         index = Array.FindIndex(primeTable, index, (flag) =&gt; !flag);\n         if (index &gt;= 1)\n         {\n            primes.Add(index);\n            index++;\n         }\n      }\n   }\n\n   public int[] GetAllPrimes()\n   {\n      return primes.ToArray();\n   }\n\n   public int[] GetPrimesFrom(int prime)\n   {\n      int start = primes.FindIndex((value) =&gt; value == prime);\n      if (start &lt; 0)\n         throw new NotPrimeException(prime, String.Format(&quot;{0} is not a prime number.&quot;, prime));\n      else\n         return primes.FindAll((value) =&gt; value &gt;= prime).ToArray();\n   }\n}\n</code></pre><p>The following example makes two calls to the <code>GetPrimesFrom</code> method with non-prime numbers, one of which crosses application domain boundaries. In both cases, the exception is thrown and successfully handled in client code.  </p>\n<pre><code class=\"lang-cs\" name=\"System.Exception.Class#3\">using System;\nusing System.Reflection;\n\nclass Example\n{\n   public static void Main()\n   {\n      int limit = 10000000;\n      PrimeNumberGenerator primes = new PrimeNumberGenerator(limit);\n      int start = 1000001;\n      try\n      {\n         int[] values = primes.GetPrimesFrom(start);\n         Console.WriteLine(&quot;There are {0} prime numbers from {1} to {2}&quot;,\n                           start, limit);\n      }\n      catch (NotPrimeException e)\n      {\n         Console.WriteLine(&quot;{0} is not prime&quot;, e.NonPrime);\n         Console.WriteLine(e);\n         Console.WriteLine(&quot;--------&quot;);\n      }\n\n      AppDomain domain = AppDomain.CreateDomain(&quot;Domain2&quot;);\n      PrimeNumberGenerator gen = (PrimeNumberGenerator)domain.CreateInstanceAndUnwrap(\n                                        typeof(Example).Assembly.FullName,\n                                        &quot;PrimeNumberGenerator&quot;, true,\n                                        BindingFlags.Default, null,\n                                        new object[] { 1000000 }, null, null);\n      try\n      {\n         start = 100;\n         Console.WriteLine(gen.GetPrimesFrom(start));\n      }\n      catch (NotPrimeException e)\n      {\n         Console.WriteLine(&quot;{0} is not prime&quot;, e.NonPrime);\n         Console.WriteLine(e);\n         Console.WriteLine(&quot;--------&quot;);\n      }\n   }\n}\n</code></pre><pre><code class=\"lang-vb\" name=\"System.Exception.Class#3\">Imports System.Reflection\n\nModule Example\n   Sub Main()\n      Dim limit As Integer = 10000000\n      Dim primes As New PrimeNumberGenerator(limit)\n      Dim start As Integer = 1000001\n      Try\n         Dim values() As Integer = primes.GetPrimesFrom(start)\n         Console.WriteLine(&quot;There are {0} prime numbers from {1} to {2}&quot;,\n                           start, limit)\n      Catch e As NotPrimeException\n         Console.WriteLine(&quot;{0} is not prime&quot;, e.NonPrime)\n         Console.WriteLine(e)\n         Console.WriteLine(&quot;--------&quot;)\n      End Try\n\n      Dim domain As AppDomain = AppDomain.CreateDomain(&quot;Domain2&quot;)\n      Dim gen As PrimeNumberGenerator = domain.CreateInstanceAndUnwrap(\n                                        GetType(Example).Assembly.FullName,\n                                        &quot;PrimeNumberGenerator&quot;, True,\n                                        BindingFlags.Default, Nothing,\n                                        {1000000}, Nothing, Nothing)\n      Try\n         start = 100\n         Console.WriteLine(gen.GetPrimesFrom(start))\n      Catch e As NotPrimeException\n         Console.WriteLine(&quot;{0} is not prime&quot;, e.NonPrime)\n         Console.WriteLine(e)\n         Console.WriteLine(&quot;--------&quot;)\n      End Try\n   End Sub\nEnd Module\n&#39; The example displays the following output:\n&#39;      1000001 is not prime\n&#39;      NotPrimeException: 1000001 is not a prime number.\n&#39;         at PrimeNumberGenerator.GetPrimesFrom(Int32 prime)\n&#39;         at Example.Main()\n&#39;      --------\n&#39;      100 is not prime\n&#39;      NotPrimeException: 100 is not a prime number.\n&#39;         at PrimeNumberGenerator.GetPrimesFrom(Int32 prime)\n&#39;         at Example.Main()\n&#39;      --------\n</code></pre></li>\n</ol>\n<h2 id=\"windows-runtime-and-includenetv451addincludesnet-v451-mdmd\">Windows Runtime and .NET Framework 4.5.1</h2>\n<p> In .NET for Windows 8.x Store apps for Windows 8, some exception information is typically lost when an exception is propagated through non-.NET Framework stack frames. Starting with the .NET Framework 4.5.1 and Windows 8.1, the common language runtime continues to use the original Exception object that was thrown unless that exception was modified in a non-.NET Framework stack frame.</p>\n\r\n  \r\n  \r\n  \t\t<section>\r\n  \t\t\t<h2 class=\"accented \">Constructors\r\n  \t\t</h2>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception__ctor\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">Exception()</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Initializes a new instance of the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> class.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public Exception ();</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>This constructor initializes the <a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a> property of the new instance to a system-supplied message that describes the error and takes into account the current system culture.  </p>\n<p> All the derived classes should provide this default constructor. The following table shows the initial property values for an instance of <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>.  </p>\n<table>\n<thead>\n<tr>\n<th>Property</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a></td>\n<td>A null reference (<code>Nothing</code> in Visual Basic).</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a></td>\n<td>A system-supplied localized description.</td>\n</tr>\n</tbody>\n</table>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception__ctor_System_String_\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">Exception(String)</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Initializes a new instance of the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> class with a specified error message.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public Exception (string message);</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"parameterList\">\r\n  \t\t\t\t\t\t\t\t<dt>message</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The message that describes the error.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>This constructor initializes the <a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a> property of the new instance by using the <code>message</code> parameter. If the <code>message</code> parameter is <code>null</code>, this is the same as calling the <a class=\"xref\" href=\"system.exception#System_Exception__ctor_\" data-linktype=\"relative-path\">Exception</a> constructor.  </p>\n<p> The following table shows the initial property values for an instance of <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>.  </p>\n<table>\n<thead>\n<tr>\n<th>Property</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a></td>\n<td>A null reference (<code>Nothing</code> in Visual Basic).</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a></td>\n<td>The error message string.</td>\n</tr>\n</tbody>\n</table>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception__ctor_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">Exception(SerializationInfo,StreamingContext)</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Initializes a new instance of the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> class with serialized data.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">protected Exception (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"parameterList\">\r\n  \t\t\t\t\t\t\t\t<dt>info</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The <a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a> that holds the serialized object data about the exception being thrown.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"parameterList\">\r\n  \t\t\t\t\t\t\t\t<dt>context</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.streamingcontext\" data-linktype=\"relative-path\">StreamingContext</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The <a class=\"xref\" href=\"system.runtime.serialization.streamingcontext\" data-linktype=\"relative-path\">StreamingContext</a> that contains contextual information about the source or destination.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfoTitle stack\">Exceptions</div>\r\n  \t\t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t\t<div class=\"subtle\">\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></span>\r\n  \t\t\t\t\t\t\t\t</div>\r\n  \t\t\t\t\t\t\t\t<p>The <code>info</code> parameter is <code>null</code>.</p>\n\r\n  \t\t\t\t\t\t\t\t</div>\r\n  \t\t\t\t\t\t\t\t<div class=\"propertyInfo stack\">\r\n  \t\t\t\t\t\t\t\t<div class=\"subtle\">\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.serializationexception\" data-linktype=\"relative-path\">SerializationException</a></span>\r\n  \t\t\t\t\t\t\t\t</div>\r\n  \t\t\t\t\t\t\t\t<p>The class name is <code>null</code> or <span class=\"xref\">stem.Exception.HResult*</span> is zero (0).</p>\n\r\n  \t\t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see <a href=\"../Topic/XML%20and%20SOAP%20Serialization.md\" data-linktype=\"relative-path\">XML and SOAP Serialization</a>.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception__ctor_System_String_System_Exception_\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">Exception(String,Exception)</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Initializes a new instance of the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> class with a specified error message and a reference to the inner exception that is the cause of this exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public Exception (string message, Exception innerException);</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"parameterList\">\r\n  \t\t\t\t\t\t\t\t<dt>message</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The error message that explains the reason for the exception.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"parameterList\">\r\n  \t\t\t\t\t\t\t\t<dt>innerException</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The exception that is the cause of the current exception, or a null reference (<code>Nothing</code> in Visual Basic) if no inner exception is specified.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property. The <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property returns the same value that is passed into the constructor, or a null reference (<code>Nothing</code> in Visual Basic) if the <a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a> property does not supply the inner exception value to the constructor.  </p>\n<p> The following table shows the initial property values for an instance of <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>.  </p>\n<table>\n<thead>\n<tr>\n<th>Property</th>\n<th>Value</th>\n</tr>\n</thead>\n<tbody>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_InnerException_\" data-linktype=\"relative-path\">InnerException</a></td>\n<td>The inner exception reference.</td>\n</tr>\n<tr>\n<td><a class=\"xref\" href=\"system.exception#System_Exception_Message_\" data-linktype=\"relative-path\">Message</a></td>\n<td>The error message string.</td>\n</tr>\n</tbody>\n</table>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t  \r\n  \t\t</section>\t\t<section>\r\n  \t\t\t<h2 class=\"accented \">Properties\r\n  \t\t</h2>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_Data\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">Data</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Gets a collection of key/value pairs that provide additional user-defined information about the exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public virtual System.Collections.IDictionary Data { get; }</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Value</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.collections.idictionary\" data-linktype=\"relative-path\">IDictionary</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>An object that implements the <a class=\"xref\" href=\"system.collections.idictionary\" data-linktype=\"relative-path\">IDictionary</a> interface and contains a collection of user-defined key/value pairs. The default is an empty collection.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>Use the <a class=\"xref\" href=\"system.collections.idictionary\" data-linktype=\"relative-path\">System.Collections.IDictionary</a> object returned by the Data property to store and retrieve supplementary information relevant to the exception. The information is in the form of an arbitrary number of user-defined key/value pairs. The key component of each key/value pair is typically an identifying string, whereas the value component of the pair can be any type of object.  </p>\n<h2 id=\"keyvalue-pair-security\">Key/Value Pair Security</h2>\n<p> The key/value pairs stored in the collection returned by the Data property are not secure. If your application calls a nested series of routines, and each routine contains exception handlers, the resulting call stack contains a hierarchy of those exception handlers. If a lower-level routine throws an exception, any upper-level exception handler in the call stack hierarchy can read and/or modify the key/value pairs stored in the collection by any other exception handler. This means you must guarantee that the information in the key/value pairs is not confidential and that your application will operate correctly if the information in the key/value pairs is corrupted.  </p>\n<h2 id=\"key-conflicts\">Key Conflicts</h2>\n<p> A key conflict occurs when different exception handlers specify the same key to access a key/value pair. Use caution when developing your application because the consequence of a key conflict is that lower-level exception handlers can inadvertently communicate with higher-level exception handlers, and this communication might cause subtle program errors. However, if you are cautious you can use key conflicts to enhance your application.  </p>\n<h2 id=\"avoiding-key-conflicts\">Avoiding Key Conflicts</h2>\n<p> Avoid key conflicts by adopting a naming convention to generate unique keys for key/value pairs. For example, a naming convention might yield a key that consists of the period-delimited name of your application, the method that provides supplementary information for the pair, and a unique identifier.  </p>\n<p> Suppose two applications, named Products and Suppliers, each has a method named Sales. The Sales method in the Products application provides the identification number (the stock keeping unit or SKU) of a product. The Sales method in the Suppliers application provides the identification number, or SID, of a supplier. Consequently, the naming convention for this example yields the keys, &quot;Products.Sales.SKU&quot; and &quot;Suppliers.Sales.SID&quot;.  </p>\n<h2 id=\"exploiting-key-conflicts\">Exploiting Key Conflicts</h2>\n<p> Exploit key conflicts by using the presence of one or more special, prearranged keys to control processing. Suppose, in one scenario, the highest level exception handler in the call stack hierarchy catches all exceptions thrown by lower-level exception handlers. If a key/value pair with a special key exists, the high-level exception handler formats the remaining key/value pairs in the <a class=\"xref\" href=\"system.collections.idictionary\" data-linktype=\"relative-path\">IDictionary</a> object in some nonstandard way; otherwise, the remaining key/value pairs are formatted in some normal manner.  </p>\n<p> Now suppose, in another scenario, the exception handler at each level of the call stack hierarchy catches the exception thrown by the next lower-level exception handler. In addition, each exception handler knows the collection returned by the Data property contains a set of key/value pairs that can be accessed with a prearranged set of keys.  </p>\n<p> Each exception handler uses the prearranged set of keys to update the value component of the corresponding key/value pair with information unique to that exception handler. After the update process is complete, the exception handler throws the exception to the next higher-level exception handler. Finally, the highest level exception handler accesses the key/value pairs and displays the consolidated update information from all the lower-level exception handlers.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_HelpLink\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">HelpLink</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Gets or sets a link to the help file associated with this exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public virtual string HelpLink { get; set; }</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Value</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The Uniform Resource Name (URN) or Uniform Resource Locator (URL).</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>The return value, which represents a help file, is a URN or URL. For example, the <code>HelpLink</code> value could be:  </p>\n<p> &quot;file:///C:/Applications/Bazzal/help.html#ErrorNum42&quot;</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_HResult\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">HResult</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Gets or sets HRESULT, a coded numerical value that is assigned to a specific exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public int HResult { get; protected set; }</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Value</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.int32\" data-linktype=\"relative-path\">Int32</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The HRESULT value.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>HRESULT is a 32-bit value, divided into three different fields: a severity code, a facility code, and an error code. The severity code indicates whether the return value represents information, warning, or error. The facility code identifies the area of the system responsible for the error. The error code is a unique number that is assigned to represent the exception. Each exception is mapped to a distinct HRESULT. When managed code throws an exception, the runtime passes the HRESULT to the COM client. When unmanaged code returns an error, the HRESULT is converted to an exception, which is then thrown by the runtime. For information about HRESULT values and their corresponding .NET Framework exceptions, see <a href=\"../Topic/How%20to:%20Map%20HRESULTs%20and%20Exceptions.md\" data-linktype=\"relative-path\">How to: Map HRESULTs and Exceptions</a>. See <a href=\"http://msdn.microsoft.com/library/windows/desktop/aa378137.aspx\" data-linktype=\"external\">Common HRESULT Values</a> in the Windows documentation for a list of the values you are most likely to encounter.  </p>\n<p> Starting with the .NET Framework 4.5, the HResult property&#39;s setter is protected, whereas its getter is public.  In previous versions of the .NET Framework, both getter and setter are protected.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_InnerException\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">InnerException</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Gets the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> instance that caused the current exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public Exception InnerException { get; }</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Value</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>An object that describes the error that caused the current exception. The InnerException property returns the same value as was passed into the <span class=\"xref\">stem.Exception.#ctor(System.String,System.Exception)</span> constructor, or <code>null</code> if the inner exception value was not supplied to the constructor. This property is read-only.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>When an exception <code>X</code> is thrown as a direct result of a previous exception <code>Y</code>, the InnerException property of <code>X</code> should contain a reference to <code>Y</code>.  </p>\n<p> Use the InnerException property to obtain the set of exceptions that led to the current exception.  </p>\n<p> You can create a new exception that catches an earlier exception. The code that handles the second exception can make use of the additional information from the earlier exception to handle the error more appropriately.  </p>\n<p> Suppose that there is a function that reads a file and formats the data from that file. In this example, as the code tries to read the file, an <a class=\"xref\" href=\"system.io.ioexception\" data-linktype=\"relative-path\">IOException</a> is thrown. The function catches the <a class=\"xref\" href=\"system.io.ioexception\" data-linktype=\"relative-path\">IOException</a> and throws a <a class=\"xref\" href=\"system.io.filenotfoundexception\" data-linktype=\"relative-path\">FileNotFoundException</a>. The <a class=\"xref\" href=\"system.io.ioexception\" data-linktype=\"relative-path\">IOException</a> could be saved in the InnerException property of the <a class=\"xref\" href=\"system.io.filenotfoundexception\" data-linktype=\"relative-path\">FileNotFoundException</a>, enabling the code that catches the <a class=\"xref\" href=\"system.io.filenotfoundexception\" data-linktype=\"relative-path\">FileNotFoundException</a> to examine the cause of the initial error.  </p>\n<p> The InnerException property, which holds a reference to the inner exception, is set upon initialization of the exception object.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_Message\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">Message</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Gets a message that describes the current exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public virtual string Message { get; }</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Value</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The error message that explains the reason for the exception, or an empty string (&quot;&quot;).</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>Error messages target the developer who is handling the exception. The text of the Message property should completely describe the error and, when possible, should also explain how to correct the error. Top-level exception handlers may display the message to end-users, so you should ensure that it is grammatically correct and that each sentence of the message ends with a period. Do not use question marks or exclamation points. If your application uses localized exception messages, you should ensure that they are accurately translated.  </p>\n<div class=\"IMPORTANT\"><h5>Important</h5><p> Do not disclose sensitive information in exception messages without checking for the appropriate permissions.  </p>\n</div>\n<p> The value of the Message property is included in the information returned by <a class=\"xref\" href=\"system.exception#System_Exception_ToString_\" data-linktype=\"relative-path\">ToString</a>.The Message property is set only when creating an <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a>. If no message was supplied to the constructor for the current instance, the system supplies a default message that is formatted using the current system culture.  </p>\n<h2 id=\"windows-runtime-and-includenetv451addincludesnet-v451-mdmd\">Windows Runtime and .NET Framework 4.5.1</h2>\n<p> Starting with the .NET Framework 4.5.1 and Windows 8.1, the fidelity of error messages from exceptions that are propagated from Windows Runtime types and members that are not part of the .NET Framework is improved. In particular, exception messages from Visual C++ component extensions (C++/CX) are now propagated back into .NET Framework <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> objects.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_Source\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">Source</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Gets or sets the name of the application or the object that causes the error.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public virtual string Source { get; set; }</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Value</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The name of the application or the object that causes the error.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfoTitle stack\">Exceptions</div>\r\n  \t\t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t\t<div class=\"subtle\">\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentexception\" data-linktype=\"relative-path\">ArgumentException</a></span>\r\n  \t\t\t\t\t\t\t\t</div>\r\n  \t\t\t\t\t\t\t\t<p>The object must be a runtime <a class=\"xref\" href=\"system.reflection\" data-linktype=\"relative-path\">System.Reflection</a> object</p>\n\r\n  \t\t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>If the Source property is not set explicitly, the runtime automatically sets it to the name of the assembly in which the exception originated.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_StackTrace\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">StackTrace</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Gets a string representation of the immediate frames on the call stack.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public virtual string StackTrace { get; }</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Value</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>A string that describes the immediate frames of the call stack.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>The execution stack keeps track of all the methods that are in execution at a given instant. A trace of the method calls is called a stack trace. The stack trace listing provides a way to follow the call stack to the line number in the method where the exception occurs.  </p>\n<p> The StackTrace property returns the frames of the call stack that originate at the location where the exception was thrown. You can obtain information about additional frames in the call stack by creating a new instance of the <a class=\"xref\" href=\"system.diagnostics.stacktrace\" data-linktype=\"relative-path\">System.Diagnostics.StackTrace</a> class and using its <a class=\"xref\" href=\"system.diagnostics.stacktrace#System_Diagnostics_StackTrace_ToString_\" data-linktype=\"relative-path\">ToString</a> method.  </p>\n<p> The common language runtime (CLR) updates the stack trace whenever an exception is thrown in application code (by using the <code>throw</code> keyword). If the exception was rethrown in a method that is different than the method where it was originally thrown, the stack trace contains both the location in the method where the exception was originally thrown, and the location in the method where the exception was rethrown. If the exception is thrown, and later rethrown, in the same method, the stack trace only contains the location where the exception was rethrown and does not include the location where the exception was originally thrown.  </p>\n<p> The StackTrace property may not report as many method calls as expected because of code transformations, such as inlining, that occur during optimization.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_TargetSite\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">TargetSite</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Gets the method that throws the current exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public System.Reflection.MethodBase TargetSite { get; }</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Value</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.reflection.methodbase\" data-linktype=\"relative-path\">MethodBase</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The <a class=\"xref\" href=\"system.reflection.methodbase\" data-linktype=\"relative-path\">MethodBase</a> that threw the current exception.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>If the method that throws this exception is not available and the stack trace is not a null reference (<code>Nothing</code> in Visual Basic), TargetSite obtains the method from the stack trace. If the stack trace is a null reference, TargetSite also returns a null reference.  </p>\n<div class=\"NOTE\"><h5>Note</h5><p> The TargetSite property may not accurately report the name of the method in which an exception was thrown if the exception handler handles an exception across application domain boundaries.</p>\n</div>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t  \r\n  \t\t</section>\t\t<section>\r\n  \t\t\t<h2 class=\"accented \">Methods\r\n  \t\t</h2>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_GetBaseException\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">GetBaseException()</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>When overridden in a derived class, returns the <a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a> that is the root cause of one or more subsequent exceptions.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public virtual Exception GetBaseException ();</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Returns</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.exception\" data-linktype=\"relative-path\">Exception</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The first exception thrown in a chain of exceptions. If the <span class=\"xref\">stem.Exception.InnerException*</span> property of the current exception is a null reference (<code>Nothing</code> in Visual Basic), this property returns the current exception.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>A chain of exceptions consists of a set of exceptions such that each exception in the chain was thrown as a direct result of the exception referenced in its <code>InnerException</code> property. For a given chain, there can be exactly one exception that is the root cause of all other exceptions in the chain. This exception is called the base exception and its <code>InnerException</code> property always contains a null reference.  </p>\n<p> For all exceptions in a chain of exceptions, the <code>GetBaseException</code> method must return the same object (the base exception).  </p>\n<p> Use the <code>GetBaseException</code> method when you want to find the root cause of an exception but do not need information about exceptions that may have occurred between the current exception and the first exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_GetObjectData_System_Runtime_Serialization_SerializationInfo_System_Runtime_Serialization_StreamingContext_\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">GetObjectData(SerializationInfo,StreamingContext)</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>When overridden in a derived class, sets the <a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a> with information about the exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public virtual void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"parameterList\">\r\n  \t\t\t\t\t\t\t\t<dt>info</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The <a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a> that holds the serialized object data about the exception being thrown.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"parameterList\">\r\n  \t\t\t\t\t\t\t\t<dt>context</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.runtime.serialization.streamingcontext\" data-linktype=\"relative-path\">StreamingContext</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>The <a class=\"xref\" href=\"system.runtime.serialization.streamingcontext\" data-linktype=\"relative-path\">StreamingContext</a> that contains contextual information about the source or destination.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfoTitle stack\">Exceptions</div>\r\n  \t\t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t\t<div class=\"subtle\">\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.argumentnullexception\" data-linktype=\"relative-path\">ArgumentNullException</a></span>\r\n  \t\t\t\t\t\t\t\t</div>\r\n  \t\t\t\t\t\t\t\t<p>The <code>info</code> parameter is a null reference (<code>Nothing</code> in Visual Basic).</p>\n\r\n  \t\t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p><code>GetObjectData</code> sets a <a class=\"xref\" href=\"system.runtime.serialization.serializationinfo\" data-linktype=\"relative-path\">SerializationInfo</a> with all the exception object data targeted for serialization. During deserialization, the exception is reconstituted from the <code>SerializationInfo</code> transmitted over the stream.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_GetType\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">GetType()</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Gets the runtime type of the current instance.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public Type GetType ();</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Returns</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.type\" data-linktype=\"relative-path\">Type</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>A <a class=\"xref\" href=\"system.type\" data-linktype=\"relative-path\">Type</a> object that represents the exact runtime type of the current instance.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>The GetType method exists to support the .NET Framework infrastructure, and internally invokes the fundamental method, <a class=\"xref\" href=\"system.object#System_Object_GetType_\" data-linktype=\"relative-path\">GetType</a>.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_ToString\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">ToString()</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Creates and returns a string representation of the current exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">public override string ToString ();</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t\t<div class=\"propertyInfo\">\r\n  \t\t\t\t\t\t\t<dl class=\"attributeList stack\">\r\n  \t\t\t\t\t\t\t\t<dt>Returns</dt>\r\n  \t\t\t\t\t\t\t\t<dd>\r\n  \t\t\t\t\t\t\t\t\t\t<span class=\"lang-csharp\"><a class=\"xref\" href=\"system.string\" data-linktype=\"relative-path\">String</a></span>\r\n  \t\t\t\t\t\t\t\t</dd>\r\n  \t\t\t\t\t\t\t</dl>\r\n  \t\t\t\t\t\t\t<p>A string representation of the current exception.</p>\n\r\n  \t\t\t\t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>ToString returns a representation of the current exception that is intended to be understood by humans. Where the exception contains culture-sensitive data, the string representation returned by <code>ToString</code> is required to take into account the current system culture. Although there are no exact requirements for the format of the returned string, it should attempt to reflect the value of the object as perceived by the user.  </p>\n<p> The default implementation of ToString obtains the name of the class that threw the current exception, the message, the result of calling ToString on the inner exception, and the result of calling <a class=\"xref\" href=\"system.environment#System_Environment_StackTrace_\" data-linktype=\"relative-path\">StackTrace</a>. If any of these members is <code>null</code>, its value is not included in the returned string.  </p>\n<p> If there is no error message or if it is an empty string (&quot;&quot;), then no error message is returned. The name of the inner exception and the stack trace are returned only if they are not <code>null</code>.  </p>\n<p> This method overrides <a class=\"xref\" href=\"system.object#System_Object_ToString_\" data-linktype=\"relative-path\">ToString</a>.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t  \r\n  \t\t</section>\t\t<section>\r\n  \t\t\t<h2 class=\"accented \">Events\r\n  \t\t</h2>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberNameHolder\" id=\"System_Exception_SerializeObjectState\">\r\n  \t\t\t\t\t<h3 class=\"accented\">\r\n  \t\t\t\t\t\t<span class=\"lang-csharp\">SerializeObjectState</span>        \r\n  \t\t\t\t\t</h3>\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\t\t<div class=\"memberInfo\">\r\n  \t\t\t\t\t<p>Occurs when an exception is serialized to create an exception state object that contains serialized data about the exception.</p>\n\r\n  \t\t\r\n  \t\t\t\t\t\t<pre class=\"wrap loading\"><code class=\"csharp lang-csharp\" dir=\"ltr\">protected event EventHandler&lt;System.Runtime.Serialization.SafeSerializationEventArgs&gt; SerializeObjectState;</code></pre>\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\r\n  \t\t\t\t\t\t<h4 class=\"accented\">Remarks</h4>\r\n  \t\t\t\t\t\t<p>The exception state object implements the <a class=\"xref\" href=\"system.runtime.serialization.isafeserializationdata\" data-linktype=\"relative-path\">ISafeSerializationData</a> interface.  </p>\n<p> When the SerializeObjectState event is subscribed to, the exception is deserialized and created as an empty exception. The exception&#39;s constructor is not run, and the exception state is also deserialized. The <a class=\"xref\" href=\"system.runtime.serialization.isafeserializationdata#System_Runtime_Serialization_ISafeSerializationData_CompleteDeserialization_\" data-linktype=\"relative-path\">CompleteDeserialization</a> callback method of the exception state object is then notified so that it can push deserialized data into the empty exception.  </p>\n<p> The SerializeObjectState event enables transparent exception types to serialize and deserialize exception data. Transparent code can execute commands within the bounds of the permission set it is operating within, but cannot execute, call, derive from, or contain critical code.  </p>\n<p> If the SerializeObjectState event is not subscribed to, deserialization occurs as usual using the <a class=\"xref\" href=\"system.exception#System_Exception__ctor_\" data-linktype=\"relative-path\">Exception</a> constructor.  </p>\n<p> Typically, a handler for the SerializeObjectState event is added in the exception&#39;s constructor to provide for its serialization. But because the constructor is not executed when the SerializeObjectState event handler executes, serializing a deserialized exception can throw a <a class=\"xref\" href=\"system.runtime.serialization.serializationexception\" data-linktype=\"relative-path\">SerializationException</a> exception when you try to deserialize the exception. To avoid this, you should also add the handler for the SerializeObjectState event in the <a class=\"xref\" href=\"system.runtime.serialization.isafeserializationdata#System_Runtime_Serialization_ISafeSerializationData_CompleteDeserialization_\" data-linktype=\"relative-path\">CompleteDeserialization</a> method. See the Examples section for an illustration.</p>\n\r\n  \t\t\r\n  \t\t\t\t</div>\r\n  \t\t\r\n  \t\t\r\n  \t\t  \r\n  \t\t</section>\r\n  \r\n  \r\n","outputRootRelativePath":"./","pageMetadata":"<meta name=\"author\" content=\"dotnet-bot\">\r\n<meta name=\"breadcrumb_path\" content=\"breadcrumb/toc.json\">\r\n<meta name=\"search.ms_sitename\" content=\"Docs\">\r\n<meta name=\"search.ms_docsetname\" content=\"fulldocset\">\r\n<meta name=\"locale\" content=\"en-us\">\r\n<meta name=\"site_name\" content=\"Docs\">\r\n<meta name=\"search.ms_product\" content=\"MSDN\">\r\n<meta name=\"depot_name\" content=\"MSDN.fulldocset\">\r\n<meta name=\"ref_skeleton_gitcommit\" content=\"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/501959ac03e19ac52a27aa4c6bbeb980f8b11c8c/fulldocset/System.Exception.yml\">\r\n<meta name=\"original_ref_skeleton_git_url\" content=\"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/System.Exception.yml\">\r\n<meta name=\"APIName\" content=\"System.Exception\">\r\n<meta name=\"APIName\" content=\"System.Exception..ctor\">\r\n<meta name=\"APIName\" content=\"System.Exception.Data\">\r\n<meta name=\"APIName\" content=\"System.Exception.GetBaseException\">\r\n<meta name=\"APIName\" content=\"System.Exception.GetObjectData\">\r\n<meta name=\"APIName\" content=\"System.Exception.GetType\">\r\n<meta name=\"APIName\" content=\"System.Exception.HelpLink\">\r\n<meta name=\"APIName\" content=\"System.Exception.HResult\">\r\n<meta name=\"APIName\" content=\"System.Exception.InnerException\">\r\n<meta name=\"APIName\" content=\"System.Exception.Message\">\r\n<meta name=\"APIName\" content=\"System.Exception.SerializeObjectState\">\r\n<meta name=\"APIName\" content=\"System.Exception.add_SerializeObjectState\">\r\n<meta name=\"APIName\" content=\"System.Exception.remove_SerializeObjectState\">\r\n<meta name=\"APIName\" content=\"System.Exception.Source\">\r\n<meta name=\"APIName\" content=\"System.Exception.StackTrace\">\r\n<meta name=\"APIName\" content=\"System.Exception.TargetSite\">\r\n<meta name=\"APIName\" content=\"System.Exception.ToString\">\r\n<meta name=\"APILocation\" content=\"mscorlib.dll\">\r\n<meta name=\"TopicType\" content=\"apiref\">\r\n<meta name=\"APIType\" content=\"Assembly\">\r\n<meta name=\"updated_at\" content=\"2017-03-01 01:37 AM\">\r\n<meta name=\"document_id\" content=\"fba2c783-fb7a-fecb-2218-d6193d28e2a2\">\r\n<meta name=\"pagetype\" content=\"Reference\">\r\n<meta name=\"description\" content=\"Represents errors that occur during application execution.  \n To browse the .NET Framework source code for this type, see the Reference Source.\n\">\r\n<meta name=\"toc_rel\" content=\"_splitted/System/toc.json\">\r\n<meta name=\"source_url\" content=\"\">\r\n<meta name=\"ms.assetid\" content=\"System.Exception\">\r\n","rawMetadata":{"author":"dotnet-bot","breadcrumb_path":"breadcrumb/toc.json","search.ms_sitename":"Docs","search.ms_docsetname":"fulldocset","version":null,"_op_canonicalUrlPrefix":"https://ppe.docs.microsoft.com/en-us/fulldotnet/","locale":"en-us","site_name":"Docs","search.ms_product":"MSDN","_op_openToPublicContributors":true,"depot_name":"MSDN.fulldocset","_op_gitRefSkeletonCommitHistory":[{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"use plugin in master","commit_sha":"501959ac03e19ac52a27aa4c6bbeb980f8b11c8c","commit_date":"2017-03-01 09:31:20 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"switch from platform to version","commit_sha":"78cdacb5ca782478af490a6b30c3a2cb2b6b873e","commit_date":"2017-02-28 15:09:51 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"update platforms","commit_sha":"39ad5a8919a59afc93a79ac4bd8e07c3b471b37a","commit_date":"2017-02-28 10:38:59 +0800"},{"author_name":"Tianqi Zhang","author_email":"tianzh@microsoft.com","committer_name":"Tianqi Zhang","comitter_email":"tianzh@microsoft.com","message":"checkin yml","commit_sha":"da161b792852497df7140d7768cee2eccd9cb43f","commit_date":"2017-02-28 09:36:15 +0800"}],"ref_skeleton_gitcommit":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/501959ac03e19ac52a27aa4c6bbeb980f8b11c8c/fulldocset/System.Exception.yml","original_ref_skeleton_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/System.Exception.yml","open_to_public_contributors":true,"api_name":["System.Exception","System.Exception..ctor","System.Exception.Data","System.Exception.GetBaseException","System.Exception.GetObjectData","System.Exception.GetType","System.Exception.HelpLink","System.Exception.HResult","System.Exception.InnerException","System.Exception.Message","System.Exception.SerializeObjectState","System.Exception.add_SerializeObjectState","System.Exception.remove_SerializeObjectState","System.Exception.Source","System.Exception.StackTrace","System.Exception.TargetSite","System.Exception.ToString"],"api_location":["mscorlib.dll"],"topic_type":["apiref"],"api_type":["Assembly"],"f1_keywords":["System.Exception","System::Exception","System.Exception.#ctor","System::Exception::#ctor","System.Exception.Data","System::Exception::Data","System.Exception.GetBaseException","System::Exception::GetBaseException","System.Exception.GetObjectData","System::Exception::GetObjectData","System.Exception.GetType","System::Exception::GetType","System.Exception.HelpLink","System::Exception::HelpLink","System.Exception.HResult","System::Exception::HResult","System.Exception.InnerException","System::Exception::InnerException","System.Exception.Message","System::Exception::Message","System.Exception.SerializeObjectState","System::Exception::SerializeObjectState","System.Exception.Source","System::Exception::Source","System.Exception.StackTrace","System::Exception::StackTrace","System.Exception.TargetSite","System::Exception::TargetSite","System.Exception.ToString","System::Exception::ToString"],"dev_langs":["csharp"],"updated_at":"2017-03-01 01:37 AM","document_id":"fba2c783-fb7a-fecb-2218-d6193d28e2a2","content_git_url":"https://github.com/TianqiZhang/ECMA2YamlTestRepo2/blob/master/fulldocset/xml/System/Exception.xml","layout":"Reference","_op_layout":"Reference","pagetype":"Reference","title":"Exception class | Microsoft Docs","_op_ogTitle":"Exception class","description":"Represents errors that occur during application execution.  \n To browse the .NET Framework source code for this type, see the Reference Source.\n","toc_asset_id":"_splitted/System/toc.json","toc_rel":"_splitted/System/toc.json","source_url":"","ms.assetid":"System.Exception","canonical_url":"https://ppe.docs.microsoft.com/en-us/mergedepotdynamic/system.exception","_op_canonicalUrl":"https://ppe.docs.microsoft.com/en-us/mergedepotdynamic/system.exception","fileRelativePath":"System.Exception.html"},"themesRelativePathToOutputRoot":"_themes/"}